/**
 * THE OFFICIAL session-reference mention encoding, mirrored verbatim from the
 * deployment's `@deepseek-ai/dsh-session-reference` (the client bundle purity
 * gate forbids cross-plugin value imports — the one precedent is
 * `file-reference-grammar.ts`).
 *
 * The host's pre-step parser (`parseSessionReferenceText`) recognizes ONLY
 * this exact shape — `@[label](dsh-session:<base64url(JSON.stringify(id))>)`
 * — so ANY row the board renders must emit it byte-for-byte; the host then
 * materializes the cited session's snapshot into the prompt exactly like a
 * native mention (no agent-lookup is involved in that parse). The board's
 * own catalog rows use this mirror; `tests/session-mention.spec.ts` pins the
 * strings against fixtures generated by the deployed module.
 */
const SESSION_REFERENCE_SCHEME = 'dsh-session:'

/** base64url of a UTF-8 value (the deployed module uses Node's Buffer; the
 *  browser half uses TextEncoder + btoa — the same bytes). */
function base64urlUtf8(value: string): string {
  const bytes = new TextEncoder().encode(value)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

/** Canonical `dsh-session:` URI for one opaque session id (lossless). */
export function encodeSessionReferenceUri(sessionId: string): string {
  return `${SESSION_REFERENCE_SCHEME}${base64urlUtf8(JSON.stringify(sessionId))}`
}

/** Escape the display label for the Markdown mention (the deployed grammar:
 *  `[` `]` `\` get a backslash prefix). */
export function escapeSessionReferenceLabel(label: string): string {
  return label.replace(/[\\\]]/gu, match => `\\${match}`)
}

/** Render a host-neutral Markdown mention carrying the canonical URI. */
export function formatSessionReferenceMention(reference: { sessionId: string; label?: string }): string {
  const label = escapeSessionReferenceLabel(reference.label ?? reference.sessionId)
  return `@[${label}](${encodeSessionReferenceUri(reference.sessionId)})`
}
